# Distributed DistilGPT-2 Configuration
model:
  name: "distilgpt2"
  total_layers: 6
  cache_dir: "./models"

# Network configuration
network:
  # Set these to your actual instance IPs
  instance1_ip: "172.31.42.169"
  instance2_ip: "172.31.34.102"

# Shard definitions
shards:
  - shard_id: 0
    start_layer: 0
    end_layer: 2
    host: "0.0.0.0"
    port: 8000
    is_input_shard: true
    is_output_shard: false
    
  - shard_id: 1
    start_layer: 3
    end_layer: 5
    host: "0.0.0.0"
    port: 8000
    is_input_shard: false
    is_output_shard: true 